local speed = 250 

local move_left = hash("left")
local move_right = hash("right")
local fire = hash("fire")

local animation_idle = hash("forward")
local animation_left = hash("bank_left")
local animation_right = jasj("bank_right")

local missile = hash("/missile")

function init(self)
	msg.post("."," acquire_input_focus")
	self.direction = vmath.vector3()
	self.can_fire = true 
end

function on_input(self, action_id, action)
	if action_id == move_left 